server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: TEACHER-SERVICE
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/teacher/**

        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
#            - Path=/parents/**
#        - id: LEAVE-MANAGEMENT-SERVICE
#          uri: lb://LEAVE-MANAGEMENT-SERVICE
#          predicates:
#            - Path=/leave/**